In [1]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (20.0.0)

## Data loading

In [2]:
dtype = {
    'date': str,  
    'line': str,
    'task': str,
    'stop_seq': 'float64',    
    'stop_name': str,
    'stop_id': str,
    'scheduled_arrival': str,  
    'scheduled_departure': str,
    'actual_arrival': str,
    'actual_departure': str,
    'detection_type': str,
    'delay': 'float64',
    'stop_desc': str,
    'stop_lat': 'float64',
    'stop_lon': 'float64', 
}

In [3]:
import gc
gc.collect()

0

In [4]:
import pandas as pd
df = pd.read_parquet("/teamspace/studios/this_studio/huge_delays_removed_240625.parquet")

In [5]:
df = df.rename(columns={
    'Dzien': 'date',
    'Linia': 'line',
    'Zadanie': 'task',
    'Lp przystanku': 'stop_seq',
    'Przystanek nazwa': 'stop_name',
    'Przystanek numer': 'stop_id',
    'Rozkladowy czas przyjazdu': 'scheduled_arrival',
    'Rozkladowy czas odjazdu': 'scheduled_departure',
    'Rzeczywisty czas przyjazdu': 'actual_arrival',
    'Rzeczywisty czas odjazdu': 'actual_departure',
    'Rodzaj detekcji': 'detection_type',
})

df = df.astype(dtype)

## Data overview

In [6]:
print("Data types:")
print(df.dtypes)

print("First 5 rows:")
df.head()

Data types:
date                                           object
line                                           object
task                                           object
stop_seq                                      float64
stop_name                                      object
stop_id                                        object
scheduled_arrival                              object
scheduled_departure                            object
actual_arrival                                 object
actual_departure                               object
detection_type                                 object
Primary Key                                    object
stop_desc                                      object
stop_lat                                      float64
stop_lon                                      float64
delay                                         float64
scheduled_trip_start    datetime64[us, Europe/Warsaw]
dtype: object
First 5 rows:

,date,line,task,stop_seq,stop_name,stop_id,scheduled_arrival,scheduled_departure,actual_arrival,actual_departure,detection_type,Primary Key,stop_desc,stop_lat,stop_lon,delay,scheduled_trip_start
0,2023-01-01,10,010-01,1.0,Władysława IV,2169,2023-01-01 04:11:00,2023-01-01 04:11:00,2023-01-01 04:10:07,2023-01-01 04:10:07,1,2023-01-01-010-01-1,Władysława IV,54.39869,18.67434,-53.0,2023-01-01 04:11:00+01:00
1,2023-01-01,10,010-01,2.0,Nowy Port Góreckiego,208,2023-01-01 04:12:00,2023-01-01 04:12:00,2023-01-01 04:12:12,2023-01-01 04:12:44,2,2023-01-01-010-01-1,Nowy Port Góreckiego,54.40005,18.67098,12.0,2023-01-01 04:11:00+01:00
2,2023-01-01,10,010-01,3.0,Marynarki Polskiej,2166,2023-01-01 04:14:00,2023-01-01 04:14:00,2023-01-01 04:13:36,2023-01-01 04:14:00,2,2023-01-01-010-01-1,Marynarki Polskiej,54.39837,18.66617,-24.0,2023-01-01 04:11:00+01:00
3,2023-01-01,10,010-01,4.0,Śnieżna,2164,2023-01-01 04:16:00,2023-01-01 04:16:00,2023-01-01 04:14:56,2023-01-01 04:15:39,2,2023-01-01-010-01-1,Śnieżna,54.39228,18.65767,-64.0,2023-01-01 04:11:00+01:00
4,2023-01-01,10,010-01,5.0,Polsat Plus Arena Gdańsk,2162,2023-01-01 04:18:00,2023-01-01 04:18:00,2023-01-01 04:16:35,2023-01-01 04:17:33,2,2023-01-01-010-01-1,Polsat Plus Arena Gdańsk,54.38726,18.64840,-85.0,2023-01-01 04:11:00+01:00

## Date columns to datetime

In [7]:
datetime_cols = ['scheduled_arrival', 'scheduled_departure', 'date']

for col in datetime_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# Feature enineering

In [8]:
df['departure_year'] = df['scheduled_departure'].dt.year
df['departure_month'] = df['scheduled_departure'].dt.month
df['departure_day'] = df['scheduled_departure'].dt.day
df['departure_decimal_hour'] = (
    df['scheduled_departure'].dt.hour +
    df['scheduled_departure'].dt.minute / 60
)

df['departure_dow'] = df['date'].dt.dayofweek

In [9]:
def assign_time_of_day(hour):
    if pd.isna(hour):
        return 'unknown'
    elif hour <= 5:
        return 'night'
    elif hour <= 11:
        return 'morning'
    elif hour <= 17:
        return 'afternoon'
    elif hour <= 21:
        return 'evening'
    else:
        return 'late_evening'

In [10]:
df['time_of_day'] = df['departure_decimal_hour'].apply(assign_time_of_day)

## Adding lags (?)

# Dropping unnecesary columns

In [11]:
cols_to_drop = ['scheduled_arrival', 'scheduled_departure', 'actual_arrival', 'actual_departure', 'stop_desc', 'stop_lat', \
    'stop_lon', 'task', "date", "scheduled_trip_start", 'detection_type', 'Primary Key', 'stop_id']
df = df.drop(columns=cols_to_drop)


df = df.dropna(subset=['delay'])

In [12]:
df.columns

Index(['line', 'stop_seq', 'stop_name', 'delay', 'departure_year',
       'departure_month', 'departure_day', 'departure_decimal_hour',
       'departure_dow', 'time_of_day'],
      dtype='object')

## W&B

In [13]:
!pip install wandb

Requirement already satisfied: wandb in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (0.20.1)
Requirement already satisfied: click!=8.0.0,>=7.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (8.2.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (3.1.44)
Requirement already satisfied: packaging in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (23.2)
Requirement already satisfied: platformdirs in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (4.3.8)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (4.23.4)
Requirement already satisfied: psutil>=5.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (7.0.0)
Requirement already satisfied: pydantic<3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (2.11.7)
Requirement already satisfied: pyyaml in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (2.32.0)
Requirement already satisfied: setproctitle in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (1.3.6)
Requirement already satisfied: typing-extensions<5,>=4.8 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from wandb) (4.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pydantic<3->wandb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pydantic<3->wandb) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2025.6.15)
Requirement already satisfied: gitdb<5,>=4.0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)

In [14]:
import wandb

In [15]:
TOKEN_PATH = "/teamspace/studios/this_studio/W&B_API_TOKEN.txt"

with open(TOKEN_PATH, "r") as f:
    api_key = f.read().strip()

wandb.login(key=api_key)

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /teamspace/studios/this_studio/.netrc
wandb: Currently logged in as: s27478 (dsc-pjatk-warsaw) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [16]:
wandb.init(
    project="bus-delay-prediction",
    entity="dsc-pjatk-warsaw",
    name="pycaret"
)

## Pycaret

In [17]:
!pip install pycaret

Requirement already satisfied: pycaret in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (8.17.2)
Requirement already satisfied: ipywidgets>=7.6.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (8.1.1)
Requirement already satisfied: tqdm>=4.62.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (4.66.1)
Requirement already satisfied: numpy<1.27,>=1.21 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (1.3.2)
Requirement already satisfied: scikit-learn>1.4.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (2.0.5)
Requirement already satisfied: imbalanced-learn>=0.12.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (0.13.0)
Requirement already satisfied: category-encoders>=2.4.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (0.61.2)
Requirement already satisfied: requests>=2.27.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (2.32.4)
Requirement already satisfied: psutil>=5.9.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (7.0.0)
Requirement already satisfied: markupsafe>=2.0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (3.0.2)
Requirement already satisfied: importlib-metadata>=4.12.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (6.11.0)
Requirement already satisfied: nbformat>=4.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (5.10.4)
Requirement already satisfied: cloudpickle in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (3.1.1)
Requirement already satisfied: deprecation>=2.1.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (3.5.0)
Requirement already satisfied: matplotlib<3.8.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (3.7.5)
Requirement already satisfied: scikit-plot>=0.3.7 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (5.24.1)
Requirement already satisfied: kaleido>=0.2.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (1.0.0)
Requirement already satisfied: schemdraw==0.15 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (0.10.0)
Requirement already satisfied: statsmodels>=0.12.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (0.14.4)
Requirement already satisfied: sktime==0.26.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (2.0.4)
Requirement already satisfied: wurlitzer in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pycaret) (3.1.1)
Requirement already satisfied: packaging in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from sktime==0.26.0->pycaret) (23.2)
Requirement already satisfied: scikit-base<0.8.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: contourpy>=1.0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from matplotlib<3.8.0->pycaret) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from matplotlib<3.8.0->pycaret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from matplotlib<3.8.0->pycaret) (4.58.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from matplotlib<3.8.0->pycaret) (1.4.8)
Requirement already satisfied: pillow>=6.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from matplotlib<3.8.0->pycaret) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from matplotlib<3.8.0->pycaret) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from matplotlib<3.8.0->pycaret) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas<2.2.0->pycaret) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas<2.2.0->pycaret) (2025.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-learn>1.4.0->pycaret) (3.6.0)
Requirement already satisfied: patsy>=0.5.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from category-encoders>=2.4.0->pycaret) (1.0.1)
Requirement already satisfied: sklearn-compat<1,>=0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from imbalanced-learn>=0.12.0->pycaret) (0.1.3)
Requirement already satisfied: zipp>=0.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from importlib-metadata>=4.12.0->pycaret) (3.23.0)
Requirement already satisfied: decorator in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (5.2.1)
Requirement already satisfied: jedi>=0.16 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (0.19.2)
Requirement already satisfied: matplotlib-inline in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (0.1.7)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (2.19.2)
Requirement already satisfied: stack-data in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (0.6.3)
Requirement already satisfied: traitlets>=5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (5.14.3)
Requirement already satisfied: exceptiongroup in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (1.3.0)
Requirement already satisfied: pexpect>4.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipython>=5.5.0->pycaret) (4.9.0)
Requirement already satisfied: wcwidth in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.13)
Requirement already satisfied: comm>=0.1.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.2)
Requirement already satisfied: widgetsnbextension~=4.0.9 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.14)
Requirement already satisfied: jupyterlab-widgets~=3.0.9 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.15)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.4)
Requirement already satisfied: choreographer>=1.0.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from kaleido>=0.2.1->pycaret) (1.0.9)
Requirement already satisfied: logistro>=1.0.8 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from kaleido>=0.2.1->pycaret) (1.1.0)
Requirement already satisfied: orjson>=3.10.15 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from kaleido>=0.2.1->pycaret) (3.10.18)
Requirement already satisfied: simplejson>=3.19.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from choreographer>=1.0.5->kaleido>=0.2.1->pycaret) (3.20.1)
Requirement already satisfied: fastjsonschema>=2.15 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from nbformat>=4.2.0->pycaret) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from nbformat>=4.2.0->pycaret) (4.24.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from nbformat>=4.2.0->pycaret) (5.8.1)
Requirement already satisfied: attrs>=22.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.25.1)
Requirement already satisfied: platformdirs>=2.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret) (4.3.8)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from numba>=0.55.0->pycaret) (0.44.0)
Requirement already satisfied: ptyprocess>=0.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pexpect>4.3->ipython>=5.5.0->pycaret) (0.7.0)
Requirement already satisfied: tenacity>=6.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from plotly>=5.14.0->pycaret) (8.5.0)
Requirement already satisfied: dash>=2.9.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.1.0)
Requirement already satisfied: tsdownsample>=0.1.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.4.1)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.1)
Requirement already satisfied: Werkzeug<3.2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.3)
Requirement already satisfied: typing-extensions>=4.1.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (4.14.0)
Requirement already satisfied: retrying in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.4.0)
Requirement already satisfied: nest-asyncio in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)
Requirement already satisfied: setuptools in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (78.1.1)
Requirement already satisfied: blinker>=1.9.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from Flask<3.2,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from Flask<3.2,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from Flask<3.2,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pmdarima>=2.0.4->pycaret) (3.1.2)
Requirement already satisfied: urllib3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pmdarima>=2.0.4->pycaret) (2.5.0)
Requirement already satisfied: six>=1.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests>=2.27.1->pycaret) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests>=2.27.1->pycaret) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests>=2.27.1->pycaret) (2025.6.15)
Requirement already satisfied: executing>=1.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from stack-data->ipython>=5.5.0->pycaret) (3.0.0)
Requirement already satisfied: pure-eval in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.3)

In [18]:
import pycaret
pycaret.__version__

'3.3.2'

In [19]:
from pycaret.regression import RegressionExperiment
exp = RegressionExperiment()

In [20]:
split_index = int(len(df) * 0.9)

df_train = df.iloc[:split_index].copy()
df_test = df.iloc[split_index:].copy()

In [21]:
exp.setup(data = df_train, 
                target = 'delay',
                experiment_name='pycaret_lightning_ai',
                log_experiment='wandb',
                session_id=42,

                fold=3,
                n_jobs=-1,
          
                normalize = True,
                transformation = True,
                remove_multicollinearity = True,
                multicollinearity_threshold = 0.95,

                fold_strategy='timeseries',
                fold_shuffle=False,
                data_split_shuffle=False)

In [23]:
exp.save_experiment('my_experiment')

In [24]:
best_cpu = exp.compare_models()

Initiated  . . . . . . . . . . . . . . . . . .                 13:35:00
Status     . . . . . . . . . . . . . . . . . .          Fitting 3 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Random Forest Regressor

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

:

In [32]:
xgb_model = exp.create_model('xgboost')

In [34]:
exp.save_model(xgb_model, 'xgboost')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['stop_seq', 'departure_year',
                                              'departure_month', 'departure_day',
                                              'departure_decimal_hour',
                                              'departure_dow'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['line', 'stop_name',
                                              'time_of_day'],
                                     transformer=SimpleImputer(strategy='m...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=-1,
                               num_parallel_tree=None, random_state=42, ...))]),
 'xgboost.pkl')